import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import "./globals.css";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nice app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
